### ISSUE TITLE
NameError: name 'bar' is not defined

### ISSUE THREAD

**Issue by zyz1dmail** [guofei9987/chrplotlib#2]
[yzzhang@xx  chrplotlib]$ cat a.py
import numpy as np
from chrplotlib import animation
def update_bar(i):
    data = 10 * np.random.rand(20)
    print(bar(data, label=range(20), max_height=10))
    print('\033[{}A'.format(12))
animation(update_func=update_bar, interval=range(100), pause=0.2)

Result as below:
=========================================
Traceback (most recent call last):
  File "a.py", line 11, in <module>
    animation(update_func=update_bar, interval=range(100), pause=0.2)
  File "/home/yzzhang/dev/chrplotlib/chrplotlib/animation.py", line 12, in animation
    update_func(i)
  File "a.py", line 7, in update_bar
    print(bar(data, label=range(20), max_height=10))
NameError: name 'bar' is not defined

**Comment by guofei9987** [comment]
```
import numpy as np
from chrplotlib import bar
from chrplotlib import animation
```
